version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/zcong1993/cache

    steps:
      - checkout
      - run:
          name: get deps
          command: |
            go get golang.org/x/vgo
            vgo mod vendor
      - run:
          name: test
          command: go test ./... -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)
